package com.example.reading.service.childAgent;

import com.example.reading.dto.ActionType;
import com.example.reading.dto.AgentResponse;
import com.example.reading.dto.LearningRequest;
import com.example.reading.dto.QuizQuestionDto;
import com.example.reading.service.llm.LlmClientService;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Implements ChildAgentService for generating quizzes using LLM.
 */
@Service
public class QuizAgentService implements ChildAgentService {

    private static final String DEFAULT_SYSTEM_PROMPT = """
            You are a quiz generator. Create quiz questions based on the provided text.
            Respond with JSON: {"questions": [{"type": "MCQ", "question": "...", "options": [...], "answer": "..."}]}
            """;

    private final LlmClientService llmClientService;
    private final ObjectMapper objectMapper;
    private final String systemPrompt;

    public QuizAgentService(LlmClientService llmClientService, ObjectMapper objectMapper) {
        this.llmClientService = llmClientService;
        this.objectMapper = objectMapper;
        this.systemPrompt = loadPrompt();
    }

    @Override
    public AgentResponse generateResponse(LearningRequest request) {
        try {
            String userPrompt = "Instruction: " + request.getInstruction() + "\n\nText:\n" + request.getText();
            String llmResponse = llmClientService.chat(systemPrompt, userPrompt);
            
            List<QuizQuestionDto> questions = parseQuizQuestions(llmResponse);
            String content = objectMapper.writeValueAsString(questions);
            
            return AgentResponse.builder()
                    .action(ActionType.QUIZ)
                    .content(content)
                    .explanation("Quiz generated by LLM")
                    .build();
        } catch (Exception e) {
            // Return a marker indicating quiz generation failed - orchestrator will handle fallback
            return AgentResponse.builder()
                    .action(ActionType.QUIZ)
                    .content(null)
                    .explanation("Quiz generation failed: " + e.getMessage())
                    .build();
        }
    }

    private List<QuizQuestionDto> parseQuizQuestions(String llmResponse) throws JsonProcessingException {
        JsonNode root = objectMapper.readTree(llmResponse);
        JsonNode questionsNode = root.get("questions");
        
        if (questionsNode == null || !questionsNode.isArray()) {
            throw new JsonProcessingException("Invalid quiz format: missing 'questions' array") {};
        }

        List<QuizQuestionDto> questions = new ArrayList<>();
        for (JsonNode questionNode : questionsNode) {
            List<String> options = new ArrayList<>();
            JsonNode optionsNode = questionNode.get("options");
            if (optionsNode != null && optionsNode.isArray()) {
                for (JsonNode optionNode : optionsNode) {
                    options.add(optionNode.asText());
                }
            }

            QuizQuestionDto question = QuizQuestionDto.builder()
                    .type(questionNode.has("type") ? questionNode.get("type").asText() : "MCQ")
                    .question(questionNode.has("question") ? questionNode.get("question").asText() : "")
                    .options(options)
                    .answer(questionNode.has("answer") ? questionNode.get("answer").asText() : "")
                    .build();
            questions.add(question);
        }

        return questions;
    }

    private String loadPrompt() {
        try {
            ClassPathResource resource = new ClassPathResource("prompts/quiz_agent_prompt.md");
            return resource.getContentAsString(StandardCharsets.UTF_8);
        } catch (IOException e) {
            return DEFAULT_SYSTEM_PROMPT;
        }
    }
}
