package com.example.reading.service.childAgent;

import com.example.reading.dto.ActionType;
import com.example.reading.dto.AgentResponse;
import com.example.reading.dto.LearningRequest;
import com.example.reading.service.llm.LlmChatService;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

/**
 * Implements ChildAgentService for generating summaries using LLM.
 */
@Service
public class SummaryAgentService implements ChildAgentService {

    private static final String DEFAULT_SYSTEM_PROMPT = """
            You are an expert summarizer. Produce a concise, accurate summary of the provided text.
            """;

    private final LlmChatService llmClientService;
    private final String systemPrompt;

    public SummaryAgentService(LlmChatService llmClientService) {
        this.llmClientService = llmClientService;
        this.systemPrompt = loadPrompt();
    }

    @Override
    public AgentResponse generateResponse(LearningRequest request) {
        try {
            String userPrompt = "Instruction: " + request.getInstruction() + "\n\nText:\n" + request.getText();
            String provider = request.getProvider() != null ? request.getProvider().name() : null;
            String summaryContent = llmClientService.chat(systemPrompt, userPrompt, provider);
            
            return AgentResponse.builder()
                    .action(ActionType.SUMMARY)
                    .content(summaryContent)
                    .explanation("Summary generated by LLM")
                    .build();
        } catch (Exception e) {
            // Fallback to basic summary if LLM fails
            String text = request.getText();
            String fallbackSummary = text.length() <= 300 ? text : text.substring(0, 300);
            
            return AgentResponse.builder()
                    .action(ActionType.SUMMARY)
                    .content("Summary (fallback): " + fallbackSummary)
                    .explanation("Fallback summary: " + e.getMessage())
                    .build();
        }
    }

    private String loadPrompt() {
        try {
            ClassPathResource resource = new ClassPathResource("prompts/summary_agent_prompt.md");
            return resource.getContentAsString(StandardCharsets.UTF_8);
        } catch (IOException e) {
            return DEFAULT_SYSTEM_PROMPT;
        }
    }
}
